apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  dataset-url: "https://covid.ourworldindata.org/data/owid-covid-data.csv"
  allowed-hosts: localhost,127.0.0.1,[::1],webapp,covid-africa.info,covid-africa.com
